-- CreateTable
CREATE TABLE "registrations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "birth_date" TIMESTAMP(3) NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "rg" TEXT NOT NULL,
    "cpf" TEXT NOT NULL,
    "street_name" TEXT NOT NULL,
    "street_number" TEXT NOT NULL,
    "neighborhood" TEXT NOT NULL,
    "complement" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "is_church_member" BOOLEAN NOT NULL,
    "church_name" TEXT NOT NULL,
    "church_leader_name" TEXT NOT NULL,
    "responsible_name" TEXT NOT NULL,
    "responsible_birth_date" TIMESTAMP(3),
    "responsible_email" TEXT NOT NULL,
    "responsible_phone" TEXT NOT NULL,
    "responsible_rg" TEXT NOT NULL,
    "responsible_cpf" TEXT NOT NULL,
    "degree_of_kinship" TEXT NOT NULL,
    "is_paid" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "registrations_pkey" PRIMARY KEY ("id")
);
